export const FETCH_PRODUCTS = 'FETCH_PRODUCTS'
export const LIKE = 'LIKE'
export const UPDATE = 'UPDATE'
export const DELETE = 'DELETE'
export const CREATE = 'CREATE'
export const LOGIN = 'LOGIN'
export const SIGNUP = 'SIGNUP'